# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pr
canonical: http://hl7.org/fhir/us/davinci-pr
name: DaVinciPostableRemittance
title: Da Vinci Postable Remittance
status: active # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: Trial-Use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
publisher:
  name: HL7 International / Payer/Provider Information Exchange Work Group
  url: http://www.hl7.org/Special/committees/claims
  # email: test@example.org

dependencies:
  hl7.fhir.us.davinci-hrex:
    uri: http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex
    version: 1.1.0
    id: hrex
parameters:
  show-inherited-invariants: false
  auto-oid-root: 2.16.840.1.113883.4.642.40.49
  apply-publisher: true
  apply-contact: true
  globals-in-artifacts: true
  shownav: true


extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 1
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: claims 

pages:
  index.md:
    title: PR IG Home Page
  background.md:
    title: Reading this IG
  usecases.md:
    title: Use Cases
  credits.md:
    title: Project and Participants
  conformance.md:
    title: Conformance Expectations
  technical.md:
    title: Technical Expectations
  security.md:
    title: Privacy and Security
  fhirArtifacts.md:
    title: FHIR Artifacts
  artifacts.html:
    title: Artifact List
  downloads.md:
    title: Downloads
  changelog.md:
    title: Change History

menu:
  IG Home: index.html
  Background:
    Reading this IG: background.html
    Use Cases: usecases.html
    Project and Participants: credits.html
  Specification:
    Conformance Expectations: conformance.html
    Technical Expectations: technical.html
    Privacy, Safety, and Security: security.html
  FHIR Artifacts:
    Overview: fhirArtifacts.html
    Artifacts: artifacts.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
    HRex 1.1.0: new-tab {{site.data.fhir.ver.hrex}}
  Support:
    Discussion Forum: https://chat.fhir.org/#narrow/channel/440634-Da-Vinci-PR
    Project Page: https://confluence.hl7.org/pages/viewpage.action?pageId=230557166
    Implementer Support: https://confluence.hl7.org/display/DVP/Postable+Remittance+Implementer+Support
    Specification Dashboard: https://jira.hl7.org/secure/Dashboard.jspa?selectPageId=11813
    Propose a Change: https://jira.hl7.org/secure/CreateIssueDetails!init.jspa?pid=10405&amp;issuetype=10600&amp;customfield_11302=FHIR-us-davinci-pr
    Downloads: downloads.html
  Change Log: changelog.html
  History: http://hl7.org/fhir/us/davinci-pr/history.html

instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  #
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  #
  # setId: always # always | standalone-only
